source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AZImagePicker_Example', :exclusive => true do
  pod "AZImagePicker", :path => "../"
end

target 'AZImagePicker_Tests', :exclusive => true do
  pod "AZImagePicker", :path => "../"

  
end
